### ISSUE TITLE
Wrong placement in the research menu

### ISSUE THREAD

**Issue by Hedede** [emipa606/CentralizedClimateControl#15]
Looks like the placement wasn't updated for the recent releases. See screenshots.

I have enabled all DLCs (ideology, royalty, biotech) and disabled all mods that are not dependencies of this one.
Brand new save, however, that doesn't matter, it all boils down to ResearchProjects.xml. Maybe add new tab?

![image](https://user-images.githubusercontent.com/1663596/207272102-921b828f-45a8-4df0-8dd2-af781c76d31a.png)

**Comment by emipa606** [comment]
Thanks for the report, should be fixed in 8b97049
