### ISSUE TITLE
Suggestion: Highlight Pipe-Network when Category is active

### ISSUE THREAD

**Issue by BrainInBlack** [emipa606/CentralizedClimateControl#2]
It would be nice if the pipes where highlited when  the category is active, similar to the power network when the power category is active.

**Comment by emipa606** [comment]
The thing is that since there are three types of pipes the original author chose to highlight each color when that color is selected. I dont know if its possible to see all colored pipes in the same cell at the same time.

**Comment by BrainInBlack** [comment]
The different colours are only relevant when putting down new pipes, but when placing vents it would be awesome to see where the pipes already are and if the player has to lay new pipes to the desired place, without having to select the pipe-tool each time you placed some vents.

In short, just a gray highlight if there is a pipe is more than enough.

**Comment by emipa606** [comment]
I see, perhaps there is some easy way to add it. Ill look into it

**Comment by emipa606** [comment]
Could not really find out how to fix this
