### ISSUE TITLE
[BUG] some problems for complex networks

### ISSUE THREAD

**Issue by luoluo39** [emipa606/CentralizedClimateControl#20]
some problems happens for complex networks, still figuring out what happened. 
so the current version is not suitable for release
(buildings was not properly linked)

**Comment by emipa606** [comment]
So, the update should be reverted?

**Comment by luoluo39** [comment]
> So, the update should be reverted?

I don't know how the current version is being released works, but I tested it with my latest version and found some potential issues. Perhaps not necessary to reverted, but more debugging is needed

**Comment by emipa606** [comment]
All right, Ill keep it up and well see if it causes issues for someone.

**Comment by luoluo39** [comment]
I thought you were referring to updates on GitHub. The update on Steam absolutely needs to be reverted because the pipes are working fine, but there may be some issues with the large devices connected with single pipe (divided into two networks)

**Comment by emipa606** [comment]
I see, I always publish to both places so there are no differences for those using the non-steam release of the mod. 
Can you describe in more detail so I can test it myself?

**Comment by luoluo39** [comment]
![image](https://github.com/emipa606/CentralizedClimateControl/assets/50005638/035c53fd-924a-44ef-8530-0fb4562eed7a)
The airflow they display are 1500, 1500, 3000, 3000.
which should be 6000 for all of them
they are divided into different networks

**Comment by luoluo39** [comment]
![image](https://github.com/emipa606/CentralizedClimateControl/assets/50005638/9a3d4105-cfdf-4882-a166-f987bb79a9dc)
But after adding more pipes, the problem fixed

**Comment by luoluo39** [comment]
This is my fault and I didn't find it in time. I will try to identify the problem and fix it as soon as possible

**Comment by emipa606** [comment]
No worries, the mod is reverted. Take your time :)

Something do seem off with the larger buildings, tried to add a small freezer and it does not seem to work with the larger AC:
![image](https://github.com/emipa606/CentralizedClimateControl/assets/6932991/15ce69c7-b90c-4cba-af7f-926e79b465ed)
![image](https://github.com/emipa606/CentralizedClimateControl/assets/6932991/dc7792b5-acff-45ee-8ff2-2bc99ea182c0)
![image](https://github.com/emipa606/CentralizedClimateControl/assets/6932991/7c3cf4f5-84be-4a83-a847-7802edae2d2c)

**Comment by emipa606** [comment]
It does work with the smaller AC in the same place however

**Comment by luoluo39** [comment]
Is it possible for a building to show gridID on info panel, with debug build?
this will be useful

**Comment by emipa606** [comment]
I think it would be fine with just adding it or any extra debug info if god-mode is active.

**Comment by luoluo39** [comment]
that is because a wrong argument is used while calling `EnqueueNeighborCells`.
the position should be `intVec` inside the foreach, not the `toVisitPos `outside. this is a little mistake but caused big bug
If the tests are ok, I will submit a PR to apply this change

**Comment by luoluo39** [comment]
fix confirmed
![image](https://github.com/emipa606/CentralizedClimateControl/assets/50005638/bd08559d-3803-4850-a034-05c59a5ce92b)

**Comment by emipa606** [comment]
Nice work, Ill publish it soon

**Comment by emipa606** [comment]
Fixed in c455425
